// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "Types.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - TypesRoot

@implementation TypesRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - TypesRoot_FileDescriptor

static GPBFileDescriptor *TypesRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"types"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Data

@implementation Data

@dynamic routesArray, routesArray_Count;

typedef struct Data__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *routesArray;
} Data__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "routesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Data_Route),
        .number = Data_FieldNumber_RoutesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Data__storage_, routesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Data class]
                                     rootClass:[TypesRoot class]
                                          file:TypesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Data__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Data_Route

@implementation Data_Route

@dynamic id_p;
@dynamic days;
@dynamic from;
@dynamic to;
@dynamic stopsArray, stopsArray_Count;

typedef struct Data_Route__storage_ {
  uint32_t _has_storage_[1];
  uint32_t days;
  uint32_t from;
  uint32_t to;
  NSString *id_p;
  NSMutableArray *stopsArray;
} Data_Route__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = Data_Route_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Data_Route__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "days",
        .dataTypeSpecific.className = NULL,
        .number = Data_Route_FieldNumber_Days,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Data_Route__storage_, days),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = Data_Route_FieldNumber_From,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Data_Route__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = Data_Route_FieldNumber_To,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Data_Route__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "stopsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Data_Route_Stop),
        .number = Data_Route_FieldNumber_StopsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Data_Route__storage_, stopsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Data_Route class]
                                     rootClass:[TypesRoot class]
                                          file:TypesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Data_Route__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    [localDescriptor setupContainingMessageClassName:GPBStringifySymbol(Data)];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Data_Route_Stop

@implementation Data_Route_Stop

@dynamic stationId;
@dynamic arrival;
@dynamic departure;
@dynamic platform;

typedef struct Data_Route_Stop__storage_ {
  uint32_t _has_storage_[1];
  uint32_t stationId;
  uint32_t arrival;
  uint32_t departure;
  uint32_t platform;
} Data_Route_Stop__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "stationId",
        .dataTypeSpecific.className = NULL,
        .number = Data_Route_Stop_FieldNumber_StationId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Data_Route_Stop__storage_, stationId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "arrival",
        .dataTypeSpecific.className = NULL,
        .number = Data_Route_Stop_FieldNumber_Arrival,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Data_Route_Stop__storage_, arrival),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "departure",
        .dataTypeSpecific.className = NULL,
        .number = Data_Route_Stop_FieldNumber_Departure,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Data_Route_Stop__storage_, departure),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "platform",
        .dataTypeSpecific.className = NULL,
        .number = Data_Route_Stop_FieldNumber_Platform,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Data_Route_Stop__storage_, platform),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Data_Route_Stop class]
                                     rootClass:[TypesRoot class]
                                          file:TypesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Data_Route_Stop__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    [localDescriptor setupContainingMessageClassName:GPBStringifySymbol(Data_Route)];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
