#ifndef TYPES_READER_H
#define TYPES_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct Stop_table *Stop_table_t;
typedef const flatbuffers_uoffset_t *Stop_vec_t;
typedef flatbuffers_uoffset_t *Stop_mutable_vec_t;
typedef const struct Route_table *Route_table_t;
typedef const flatbuffers_uoffset_t *Route_vec_t;
typedef flatbuffers_uoffset_t *Route_mutable_vec_t;
typedef const struct Root_table *Root_table_t;
typedef const flatbuffers_uoffset_t *Root_vec_t;
typedef flatbuffers_uoffset_t *Root_mutable_vec_t;
#ifndef Stop_identifier
#define Stop_identifier flatbuffers_identifier
#endif
#define Stop_type_hash ((flatbuffers_thash_t)0x4b7f7705)
#define Stop_type_identifier "\x05\x77\x7f\x4b"
#ifndef Route_identifier
#define Route_identifier flatbuffers_identifier
#endif
#define Route_type_hash ((flatbuffers_thash_t)0xd7d630be)
#define Route_type_identifier "\xbe\x30\xd6\xd7"
#ifndef Root_identifier
#define Root_identifier flatbuffers_identifier
#endif
#define Root_type_hash ((flatbuffers_thash_t)0xa1295a65)
#define Root_type_identifier "\x65\x5a\x29\xa1"



struct Stop_table { uint8_t unused__; };

static inline size_t Stop_vec_len(Stop_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Stop_table_t Stop_vec_at(Stop_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Stop_table_t, vec, i, 0)
__flatbuffers_table_as_root(Stop)

__flatbuffers_define_scalar_field(0, Stop, stationId, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, Stop, arrivalTime, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(2, Stop, departureTime, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_string_field(3, Stop, platform, 0)

struct Route_table { uint8_t unused__; };

static inline size_t Route_vec_len(Route_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Route_table_t Route_vec_at(Route_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Route_table_t, vec, i, 0)
__flatbuffers_table_as_root(Route)

__flatbuffers_define_string_field(0, Route, routeId, 0)
__flatbuffers_define_scalar_field(1, Route, operatingDays, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(2, Route, dateFrom, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(3, Route, dateTo, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_vector_field(4, Route, stops, Stop_vec_t, 0)

struct Root_table { uint8_t unused__; };

static inline size_t Root_vec_len(Root_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Root_table_t Root_vec_at(Root_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Root_table_t, vec, i, 0)
__flatbuffers_table_as_root(Root)

__flatbuffers_define_vector_field(0, Root, routes, Route_vec_t, 0)

#include "flatcc_epilogue.h"
#endif /* TYPES_READER_H */
